create table if not exists public.academic_holidays (
  id bigint generated by default as identity primary key,
  holiday_name text not null,
  holiday_date date not null,
  description text,
  holiday_type text default 'regular',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists academic_holidays_holiday_date_name_idx
  on public.academic_holidays (holiday_date, holiday_name);

create index if not exists academic_holidays_holiday_date_idx
  on public.academic_holidays (holiday_date);

create or replace function public.set_academic_holidays_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_set_academic_holidays_updated_at on public.academic_holidays;
create trigger trg_set_academic_holidays_updated_at
before update on public.academic_holidays
for each row
execute function public.set_academic_holidays_updated_at();

insert into public.academic_holidays (holiday_name, holiday_date, holiday_type)
values
  ('New Year''s Day', '2026-01-01', 'regular'),
  ('Araw ng Kagitingan', '2026-04-09', 'regular'),
  ('Labor Day', '2026-05-01', 'regular'),
  ('Independence Day', '2026-06-12', 'regular'),
  ('National Heroes Day', '2026-08-31', 'regular'),
  ('Bonifacio Day', '2026-11-30', 'regular'),
  ('Christmas Day', '2026-12-25', 'regular')
on conflict (holiday_date, holiday_name) do nothing;
